version: 2.1
orbs:
  python: circleci/python@2.1.1

executors:
  #bash-env:
    # machine:
    #  image: ubuntu-2004:202111-02
  py-3.8:
    docker:
      - image: cimg/python:3.8
  py-3.9:
    docker:
      - image: cimg/python:3.9
  py-3.10:
    docker:
      - image: cimg/python:3.10
  py-3.11:
    docker:
      - image: cimg/python:3.11

jobs:
  python_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest coverage coveralls pyyaml
          pkg-manager: pip
      - run:
          name: Pytest-Test
          command: |
            coverage run --source=. --omit="conf*",setup.py -m pytest
            coveralls

  bash_prep_data:
    executor: bash-env
    steps:
      - checkout
      - restore_cache:
          keys:
            - programs-cache
      - run:
          name: Download Sample Data
          command: |
            pwd
            ls
      - save_cache:
          key: sample_01
          paths:
            - sample_01_summary_analysis
      - save_cache:
          key: sample_02
          paths:
            - sample_02_target_analysis
      - save_cache:
          key: sample_03
          paths:
            - sample_03_grouped_target_analysis
      - save_cache:
          key: sample_04
          paths:
            - sample_04_pattern_analysis
      - save_cache:
          key: sample_05
          paths:
            - sample_05_fold_analysis
      - persist_to_workspace:
          root: ./
          paths:
            - sample_01_summary_analysis
            - sample_02_target_analysis
            - sample_03_grouped_target_analysis
            - sample_04_pattern_analysis
            - sample_05_fold_analysis

  bash_sample_1_test:
    executor: bash-env
    steps:
      - checkout
      - restore_cache:
          keys:
            - sample_01

      - attach_workspace:
          at: ./
      - run:
          name: Re-initiate Environment and Install Hybkit
          command: |
            python3 --version
            python3 setup.py install
            export PATH=$PATH:$PWD/scripts
      - run:
          name: Run Test
          command: |
            pwd
            ls


  scripts_autotest:
    executor: << parameters.py-version >>
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Re-initiate Environment and Install Hybkit
          command: |
            python setup.py install
            export PATH=$PATH:$PWD/scripts
      - run:
          name: Run Test
          command: |
            cd auto_tests
            ./auto_test.sh

workflows:
  test-python:
    jobs:
      - python_test
  test-bash:
      jobs:
        - bash_prep_data
        - bash_sample_1_test:
            requires:
              - bash_prep_data
            matrix:
              parameters:
                # os: [linux, macos]
                py-version: ["py-3.8", "py-3.9", "py-3.10", "py-3.11"]
