#!/usr/bin/env python3
# Daniel B. Stribling
# Renne Lab, University of Florida
# Hybkit Project : http://www.github.com/RenneLab/hybkit

"""
Read one or more '.hyb' format files and analyze the contained hybrid sequences.

Analysis Types:
    | segtype : Assigns types to each segment within hyb records.
    | mirna : Assigns which segments are a miRNA based on segment types.
    | target_region : Assigns the coding region of a coding segment types.
"""

import sys
import os 
import argparse
import hybkit

# Import module-level dunder-names:
from hybkit.__about__ import __author__, __contact__, __credits__, __date__, __deprecated__, \
                             __email__, __license__, __maintainer__, __status__, __version__

# Create Command-line Argument Parser
def make_parser():
    script_args = argparse.ArgumentParser(add_help=False)
    parser_components = [
                         hybkit.util.in_hybs_parser,
                         hybkit.util.out_hybs_parser,
                         hybkit.util.out_dir_parser,
                         hybkit.util.hyb_analysis_parser,
                         hybkit.util.gen_opts_parser,
                         hybkit.util.hybrecord_parser,
                        ]
    script_parser = argparse.ArgumentParser(
         parents=parser_components,
         description=__doc__.replace('|', ''),
         formatter_class=argparse.ArgumentDefaultsHelpFormatter
         )
    return script_parser

# Define main script function.
def hyb_analyze(in_hyb_files, analysis_types, out_dir='.', out_hyb_files=None,
                segtype_method=None, segtype_params=None,  
                mirna_types=None,
                verbose=False, silent=False):
    """Perform main script function."""

    if not silent:
        print('\nPerforming Analysis of Hyb Files...')
   
    # Set analysis modes
    do_segtype = ('segtype' in analysis_types)
    do_mirna = ('mirna' in analysis_types)
    do_target_region = ('target_region' in analysis_types)

    if verbose:
        print('\nPerforming Analysis Types: ' + ', '.join([x.title() for x in analysis_types]))
        print()

    # Prepare for segtype analysis.
    if do_segtype:
        if segtype_method is None:
            message = '"segtype_method" argument is required for hyb_analysis method.'
            print(message)
            raise Error(message)

        if segtype_method != make_parser().get_default('segtype_method'):
            if verbose:
                print('Setting non-default segtype finding method: %s' % segtype_method)
            params = {}
            params_method = hybkit.HybRecord.find_type_parameter_methods[segtype_method]
            if params_method is not None:
                if segtype_params is None:
                    segtype_params = (
                        hybkit.HybRecord.find_type_default_parameter_files[segtype_method])
                    if verbose:
                        print ('Using default segtype parameter file: %s' % segtype_params)
                elif verbose:
                    print('Using provided segtype parameter file: %s' % segtype_params)
                params = params_method(segtype_params)
                if verbose:
                    print()
            hybkit.HybRecord.select_find_type_method(segtype_method, params)

    if do_mirna:
        if not mirna_types:
            message = 'mirna_types required for mirna analysis.'
            print(message)
            raise RuntimeError(message)

        if verbose:
            print('Assigning types as miRNA:')
            print('   ', mirna_types, '\n')

    if do_target_region:
        message = 'Target Region Analysis is not yet implemented.'
        raise NotImplementedError(message)

    for i, in_hyb_file in enumerate(in_hyb_files):
        file_basename = os.path.basename(in_hyb_file)
        if out_hyb_files is not None:
            out_hyb_file = out_hyb_files[i]
        else:
            out_hyb_file = os.path.join(out_dir, file_basename.replace('.hyb', '_analyzed.hyb')) 

        if verbose:
            print('Analyzing File:\n    ' + in_hyb_file)
      
    
        with hybkit.HybFile.open(in_hyb_file, 'r') as in_hyb,\
             hybkit.HybFile.open(out_hyb_file, 'w') as out_hyb:
            for record in in_hyb:
                if do_segtype:
                    record.find_seg_types()
            
                if do_mirna:
                    record.mirna_analysis(mirna_types)
     
                if do_target_region:
                    pass

                out_hyb.write_record(record)

    if verbose:
        print('\nAnalysis Complete.\n')


# Execute the script function
if __name__ == '__main__':
    script_parser = make_parser()
    args = script_parser.parse_args() 
    hybkit.util.validate_args(args, script_parser)
    hybkit.HybRecord.set_namespace_settings(args, verbose=args.verbose)
    hyb_analyze(
                args.in_hyb, 
                args.analysis_types, 
                args.out_dir,
                out_hyb_files=args.out_hyb,
                segtype_method=args.segtype_method,
                segtype_params=args.segtype_params,
                mirna_types=args.mirna_types,
                verbose=args.verbose,
                silent=args.silent,
               )

